import { Link } from 'react-router-dom';
import { ArrowRight, BookOpen, Check, Download, Gift, Printer } from 'lucide-react';
import { Shell } from '@/components/Shell';
import { RegionSelector } from '@/components/RegionSelector';
import { useLanguage } from '@/i18n';
import { usePricing, formatMoney } from '@/context/PricingContext';
import { Button } from '@/components/ui/button';

export default function Pricing() {
  const { language } = useLanguage();
  const id = language === 'id';
  const { region, prices, error, refresh } = usePricing();
  const selected = region || 'OTHER';
  const table = prices?.regions[selected];
  return <Shell><main className="pricing-page">
    <header className="pricing-heading"><div><div className="eyebrow" data-testid="pricing-eyebrow"><BookOpen size={15} />{id ? 'Cerita kecil. Kenangan besar.' : 'Little stories. Big keepsakes.'}</div><h1 data-testid="pricing-heading">{id ? 'Harga yang ' : 'A story for '}<em>{id ? 'bersahabat.' : 'every budget.'}</em></h1><p data-testid="pricing-description">{id ? 'Satu kali bayar untuk setiap buku. Tidak ada langganan.' : 'One simple price per book. No subscription.'}</p></div><RegionSelector /></header>
    <section className="free-book-band" data-testid="free-book-offer"><Gift size={29} /><div><h2 data-testid="free-book-heading">{id ? 'Buku digital 8 halaman pertamamu gratis.' : 'Your first 8-page digital storybook is free.'}</h2><p data-testid="free-book-terms">{id ? 'Satu buku per akun orang tua. Ilustrasi, narasi, dan unduhan PDF termasuk.' : 'One per parent account. Illustrations, narration, and PDF download included.'}</p></div><Link to="/create?pages=8" className="btn btn-primary" data-testid="pricing-free-create">{id ? 'Buat buku gratis' : 'Create my free book'}<ArrowRight size={16} /></Link></section>
    {error && <div className="error-message" role="alert" data-testid="pricing-error">{id ? 'Harga belum dapat dimuat.' : 'Prices could not be loaded.'}<Button variant="ghost" onClick={refresh} data-testid="pricing-retry">{id ? 'Coba lagi' : 'Try again'}</Button></div>}
    {!prices && !error && <p role="status" data-testid="pricing-loading">{id ? 'Memuat harga…' : 'Loading prices…'}</p>}
    {table && <><section className="digital-pricing-section"><div className="pricing-section-heading"><h2 data-testid="digital-prices-heading"><BookOpen size={18} />{id ? 'Buku cerita digital' : 'Digital storybooks'}</h2><span data-testid="pricing-currency">{table.currency} · {selected === 'ID' ? 'Midtrans' : 'Stripe · Test mode'}</span></div><div className="digital-price-grid">{table.prices.map(row => <article className="digital-price-card" key={row.pages} data-testid={`digital-price-card-${row.pages}`}><div className="price-page-count" data-testid={`digital-pages-${row.pages}`}><b>{row.pages}</b><span>{id ? 'halaman' : 'pages'}</span></div><div className="digital-price" data-testid={`digital-price-${row.pages}`}>{formatMoney(row.digital, table.currency)}</div><p data-testid={`digital-price-note-${row.pages}`}>{row.pages === 8 ? (id ? 'Harga setelah buku gratis pertama' : 'After your first free book') : (id ? 'Untuk setiap cerita baru' : 'For each new adventure')}</p><ul><li data-testid={`digital-illustrations-${row.pages}`}><Check size={14} />{id ? 'Ilustrasi di setiap halaman' : 'Every page illustrated'}</li><li data-testid={`digital-narration-${row.pages}`}><Check size={14} />{id ? 'Narator pilihanmu' : 'Your choice of narrator'}</li><li data-testid={`digital-pdf-${row.pages}`}><Check size={14} />{id ? 'Unduh PDF gratis' : 'Free PDF download'}</li></ul><Link to={`/create?pages=${row.pages}`} className="btn btn-price" data-testid={`pricing-create-${row.pages}`}>{id ? 'Pilih buku ini' : 'Choose this book'}<ArrowRight size={15} /></Link></article>)}</div></section>
    <section className="print-pricing-section"><div className="pricing-section-heading"><h2 data-testid="print-prices-heading"><Printer size={18} />{id ? 'Jadikan kenangan tercetak' : 'Turn their story into a keepsake'}</h2><span data-testid="print-price-note">{id ? 'Biaya cetak terpisah dari buku digital' : 'Print price is additional to the digital book'}</span></div><div className="print-price-table" role="table" aria-label={id ? 'Harga buku cetak' : 'Printed book prices'}><div className="print-price-row print-price-header" role="row"><span role="columnheader">{id ? 'Halaman' : 'Pages'}</span><span role="columnheader">{id ? 'Sampul lunak' : 'Softcover'}</span><span role="columnheader">{id ? 'Sampul keras' : 'Hardcover'}</span></div>{table.prices.map(row => <div className="print-price-row" role="row" key={row.pages}><b role="cell" data-testid={`print-pages-${row.pages}`}>{row.pages}</b><span role="cell" data-testid={`softcover-price-${row.pages}`}>{formatMoney(row.softcover, table.currency)}</span><span role="cell" data-testid={`hardcover-price-${row.pages}`}>{formatMoney(row.hardcover, table.currency)}</span></div>)}</div></section></>}
    <div className="pdf-free-note" data-testid="pdf-always-free"><Download size={20} /><div><strong>{id ? 'Simpan sebagai PDF? Selalu gratis.' : 'Saving as PDF? Always free.'}</strong><p>{id ? 'Unduh setiap buku yang telah dibuat tanpa biaya tambahan.' : 'Download any of your generated books at no extra cost.'}</p></div></div>
  </main></Shell>;
}