import { useEffect, useState } from "react";

export const languages = [
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "id", label: "Bahasa Indonesia", flag: "🇮🇩" },
];

export const copy = {
  en: {
    language: "Language", interface: "Interface language", storybook: "Storybook language", choose: "Choose language",
    library: "My library", orders: "Orders", help: "Help",
    homeEyebrow: "A little magic, made for them", homeTitleA: "Big adventures.", homeTitleB: "Just their size.", homeDescription: "Turn a favourite face into a one-of-a-kind storybook they’ll read again and again.", createBook: "Create a book", viewLibrary: "View my library", loved: "Loved by 2,400+ little readers", heroLabel: "A story with", heroLabelBold: "their name on it", madeWonder: "Made with wonder", printed: "Printed & shipped", pickChapter: "Pick their first chapter", whereGo: "Where will they go?", buildStory: "Build a story",
    createEyebrow: "Your story starts here", createTitleA: "Who is the", createTitleB: "hero today?", createDescription: "Tell us a little about your favourite person. We’ll take care of the magic.", name: "Child’s first name", age: "Age", personality: "They are...", choose: "Choose", world: "Choose a world", photo: "A photo for their character", dropPhoto: "Drop a photo here", browse: "or browse", photoHint: "Front-facing works best · JPG or PNG", privacy: "Photos are only used to make your book", magic: "Make the magic", weaving: "Illustrating pages and recording the narrator… up to 90 seconds", ready: "Your story is ready", meet: "Meet", adventure: "big adventure.", readyDescription: "A 32-page tale with illustrations shaped by your photo — for", openStory: "Open storybook", createError: "We couldn’t make the story just now. Please try again.",
    storyLoading: "Opening their story...", chapter: "Chapter", backLibrary: "Library", orderPhysical: "Order a physical copy", previous: "Previous page", next: "Next page", storyError: "We couldn’t open this story.", readAloud: "Read aloud", stopReading: "Stop reading", muteNarrator: "Mute narrator", unmuteNarrator: "Unmute narrator", narrationUnavailable: "Narration not available for this page.",
    checkoutBack: "Back to library", checkoutTitleA: "Make it", checkoutTitleB: "real.", checkoutDescription: "A keepsake for bedtime now, and every bedtime after.", cover: "Choose your cover", hardcover: "Hardcover", softcover: "Softcover", send: "Where should we send it?", fullName: "Full name", email: "Email address", address: "Street address", city: "City", postal: "Postal code", secure: "Secure checkout", paymentHint: "Payment is simulated for this preview. Stripe-ready for launch.", placeOrder: "Place my order", orderError: "We couldn’t place that order. Please check your details and try again.", confirmed: "Order confirmed", onWayA: "It’s on its way", onWayB: "to storyland.", confirmedDescription: "We’ll send a little note when your book begins printing.", track: "Track my order",
    dashEyebrow: "Your little library", welcomeA: "Welcome back,", welcomeB: "storyteller.", createAnother: "Create another book", stories: "My storybooks", saved: "saved", firstWaiting: "Your first story is waiting", firstDescription: "Make something magical in under a minute.", startCreating: "Start creating", printOrders: "Print orders", ordersCount: "orders", noOrders: "No print orders yet. Your next keepsake could be here.", created: "Created just now",
    adminEyebrow: "Studio desk", printA: "Print", printB: "orders.", adminView: "ADMIN VIEW", incoming: "Incoming", production: "In production", shipped: "Shipped", customer: "Customer", book: "Book", newOrders: "New orders will appear here.", orderReceived: "Order received",
  },
  id: {
    language: "Bahasa", interface: "Bahasa antarmuka", storybook: "Bahasa buku cerita", choose: "Pilih bahasa",
    library: "Perpustakaan saya", orders: "Pesanan", help: "Bantuan",
    homeEyebrow: "Sedikit keajaiban untuk mereka", homeTitleA: "Petualangan besar.", homeTitleB: "Seukuran mereka.", homeDescription: "Ubah wajah kesayangan menjadi buku cerita unik yang akan mereka baca berulang kali.", createBook: "Buat buku", viewLibrary: "Lihat perpustakaan", loved: "Disukai oleh 2.400+ pembaca kecil", heroLabel: "Cerita dengan", heroLabelBold: "nama mereka", madeWonder: "Dibuat dengan keajaiban", printed: "Dicetak & dikirim", pickChapter: "Pilih bab pertama", whereGo: "Mereka akan pergi ke mana?", buildStory: "Buat cerita",
    createEyebrow: "Cerita dimulai di sini", createTitleA: "Siapa", createTitleB: "pahlawannya?", createDescription: "Ceritakan sedikit tentang orang kesayanganmu. Kami yang akan mengurus keajaibannya.", name: "Nama depan anak", age: "Usia", personality: "Mereka...", choose: "Pilih", world: "Pilih dunia", photo: "Foto untuk karakter mereka", dropPhoto: "Letakkan foto di sini", browse: "atau cari", photoHint: "Wajah menghadap depan · JPG atau PNG", privacy: "Foto hanya digunakan untuk membuat buku", magic: "Buat keajaiban", weaving: "Melukis halaman dan merekam pencerita… hingga 90 detik", ready: "Cerita sudah siap", meet: "Kenali", adventure: "petualangan besar.", readyDescription: "Kisah 32 halaman dengan ilustrasi terinspirasi foto — untuk", openStory: "Buka buku cerita", createError: "Cerita belum bisa dibuat. Silakan coba lagi.",
    storyLoading: "Membuka cerita...", chapter: "Bab", backLibrary: "Perpustakaan", orderPhysical: "Pesan buku fisik", previous: "Halaman sebelumnya", next: "Halaman berikutnya", storyError: "Cerita belum bisa dibuka.", readAloud: "Bacakan", stopReading: "Berhenti", muteNarrator: "Bisukan pencerita", unmuteNarrator: "Aktifkan suara", narrationUnavailable: "Narasi belum tersedia untuk halaman ini.",
    checkoutBack: "Kembali ke perpustakaan", checkoutTitleA: "Jadikan", checkoutTitleB: "nyata.", checkoutDescription: "Kenang-kenangan untuk waktu tidur sekarang dan seterusnya.", cover: "Pilih sampul", hardcover: "Sampul keras", softcover: "Sampul lembut", send: "Kirim ke mana?", fullName: "Nama lengkap", email: "Alamat email", address: "Alamat jalan", city: "Kota", postal: "Kode pos", secure: "Pembayaran aman", paymentHint: "Pembayaran disimulasikan untuk pratinjau ini. Siap menggunakan Stripe.", placeOrder: "Pesan sekarang", orderError: "Pesanan belum bisa dibuat. Periksa detail dan coba lagi.", confirmed: "Pesanan dikonfirmasi", onWayA: "Pesananmu sedang menuju", onWayB: "negeri cerita.", confirmedDescription: "Kami akan mengirim kabar saat bukumu mulai dicetak.", track: "Lacak pesanan",
    dashEyebrow: "Perpustakaan kecilmu", welcomeA: "Selamat datang kembali,", welcomeB: "pencerita.", createAnother: "Buat buku lagi", stories: "Buku ceritaku", saved: "tersimpan", firstWaiting: "Cerita pertamamu menunggu", firstDescription: "Buat sesuatu yang ajaib dalam satu menit.", startCreating: "Mulai membuat", printOrders: "Pesanan cetak", ordersCount: "pesanan", noOrders: "Belum ada pesanan cetak. Kenang-kenanganmu bisa ada di sini.", created: "Dibuat baru saja",
    adminEyebrow: "Meja studio", printA: "Pesanan", printB: "cetak.", adminView: "TAMPILAN ADMIN", incoming: "Masuk", production: "Dalam produksi", shipped: "Dikirim", customer: "Pelanggan", book: "Buku", newOrders: "Pesanan baru akan muncul di sini.", orderReceived: "Pesanan diterima",
  },
};

export function useLanguage() {
  const [language, setLanguage] = useState(() => window.localStorage.getItem("kids-storybook-ui") || "en");
  useEffect(() => { window.localStorage.setItem("kids-storybook-ui", language); document.documentElement.lang = language; window.dispatchEvent(new CustomEvent("kids-storybook-language", { detail: language })); }, [language]);
  useEffect(() => { const syncLanguage = event => setLanguage(event.detail); window.addEventListener("kids-storybook-language", syncLanguage); return () => window.removeEventListener("kids-storybook-language", syncLanguage); }, []);
  return { language, setLanguage, text: copy[language] };
}